spring:
  application:
    name: PricingService  h2:    console:      enabled: true  datasource:    url: jdbc:h2:mem:price 
    platform: h2    driver-class-name: org.h2.Driver
    
server:  port: 8764
eureka:         #tells about the Eureka server details and its refresh time
 instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
 client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
     enabled: true
    enabled: true
